### PR TITLE
Added russian translation

### PR DESCRIPTION
**Pull request by Cpyte-Engine-Developer**

### CODE REVIEW

**Comment by joe7575** [comment]
Thanks for the translation. I will add your file to the mod [techage](https://github.com/joe7575/techage).
With the next release, it will be part of techage_modpack

**Comment by Cpyte-Engine-Developer** [comment]
Ok

**Comment by Cpyte-Engine-Developer** [comment]
How can i add translation for construction board?

**Comment by joe7575** [comment]
All manuals as markdown files are here: https://github.com/joe7575/techage/tree/master/manuals
You can download the English versions for translation:

- manual_EN.md
- manual_ta1_EN.md
- manual_ta2_EN.md
- manual_ta3_EN.md
- manual_ta4_EN.md
- manual_ta5_EN.md

Send me/PR your files, I will then integrate the files into the generator for the construction board.

**Pull request closed without merging**
